join_report.log
re.compile('^[0-9]+ reads; of these:')
Alignments/Reports/agregated_report.tsv
0
    300 (32.79%) aligned concordantly 0 times
    383 (41.86%) aligned concordantly exactly 1 time
16
    783 (83.39%) aligned concordantly 0 times
    57 (6.07%) aligned concordantly exactly 1 time
32
    179 (18.40%) aligned concordantly 0 times
    532 (54.68%) aligned concordantly exactly 1 time
48
    694 (70.17%) aligned concordantly 0 times
    106 (10.72%) aligned concordantly exactly 1 time
Traceback (most recent call last):
  File "/mnt/Disc4T/Projects/Miniprojects/Nextflow/First_Pipe/bin/parse_bwt2_reports.py", line 86, in <module>
    parse_agregated_report(report_file, linestart, out_file)
  File "/mnt/Disc4T/Projects/Miniprojects/Nextflow/First_Pipe/bin/parse_bwt2_reports.py", line 74, in parse_agregated_report
    out_df.to_csv(out_name, sep='\t')
  File "/home/lucas/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/lucas/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/lucas/.local/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'Alignments/Reports/agregated_report.tsv'
